# Generated by Django 3.1 on 2020-08-25 09:18

from django.db import migrations, models
import django.db.models.deletion
import programmer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to=programmer.models.user_directory_path)),
                ('programmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmer.programmer')),
            ],
        ),
    ]
